PANDAS

In [1]:
import numpy as np
print(np.__version__)

2.5.3

In [2]:
import pandas as pd
print(pd.__version__)

3.0.6


# Pandas Challenge 1/100
## Topic: Pandas Fundamentals
**Difficulty:** Easy (Placement Foundation)
### Dataset
Create the following DataFrame exactly.
| Name | Age | Marks |
|------|-----|-------|
| Alice | 20 | 85 |
| Bob | 21 | 92 |
| Charlie | 19 | 78 |
| David | 22 | 95 |
| Eva | 20 | 88 |
### Tasks
1. Import Pandas.
2. Create the DataFrame using `pd.DataFrame()`.
3. Store it in a variable named `df`.
4. Print the DataFrame.

In [22]:
data={
    "Name":["Alice", "Bob", "Charlie", "David", "Eva"],
    "Age":[20,21,19,22,20],
    "Marks":[85,92,78,95,88]
}
df=pd.DataFrame(data)
df

      Name  Age  Marks
0    Alice   20     85
1      Bob   21     92
2  Charlie   19     78
3    David   22     95
4      Eva   20     88


# Pandas Challenge 2/100

## Topic: Creating a Series

**Difficulty:** Easy (Placement Foundation)

### Dataset

Create a Series containing the following marks:

| Student | Marks |
|---------|------:|
| A | 85 |
| B | 90 |
| C | 78 |
| D | 92 |
| E | 88 |

Use the student names (`A`, `B`, `C`, `D`, `E`) as the **custom index**.

### Tasks

1. Create a Series named `marks`.
2. Use the student names as the custom index.
3. Display the Series.
4. Display only the value of student **C**.

In [23]:
marks={
    "A": 85,
    "B": 90,
    "C": 78,
    "D": 92,
    "E": 88
}
series=pd.Series(marks)

#or

index=('A', 'B', 'C', 'D', 'E')
marks=[85,90,78,92,88]
series1=pd.Series(marks, index=index)

series

A    85
B    90
C    78
D    92
E    88
dtype: int64


# Pandas Challenge 3/100

## Topic: Reading and Writing Data

**Difficulty:** Easy (Placement Foundation)

### Dataset

Create the following DataFrame.

| Name | Department | Salary |
|------|------------|--------|
| Alice | HR | 45000 |
| Bob | IT | 60000 |
| Charlie | Finance | 55000 |
| David | IT | 70000 |
| Eva | HR | 48000 |

### Tasks

1. Create the DataFrame and store it in `df`.
2. Save it as a CSV file named `employees.csv`.
3. While saving, make sure the DataFrame index is **not** written to the file.
4. Read the same CSV back into a new variable named `emp_df`.
5. Display `emp_df`.

In [24]:
data={
    "Name":["Alice", "Bob", "Charlie", "David", "Eva"],
    "Department":["HR","IT","Finance","IT","HR"],
    "Salary":[45000, 60000, 55000, 70000, 48000]
}
df=pd.DataFrame(data)
df.to_csv('employees.csv', index=False)
emp_df = pd.read_csv('employees.csv')
print(emp_df)

      Name Department  Salary
0    Alice         HR   45000
1      Bob         IT   60000
2  Charlie    Finance   55000
3    David         IT   70000
4      Eva         HR   48000


# Pandas Challenge 4/100

## Topic: Exploring Data

**Difficulty:** Easy (Placement Foundation)

### Tasks

1. Display the first **3** rows.
2. Display the last **2** rows.
3. Print the shape of the DataFrame.
4. Print all column names.
5. Print the data type of each column.
6. Display the dataset summary using `info()`.
7. Display the numerical summary using `describe()`.

In [25]:
df = pd.DataFrame({
    "Name": ["Alice", "Bob", "Charlie", "David", "Eva", "Frank"],
    "Department": ["HR", "IT", "Finance", "IT", "HR", "Sales"],
    "Salary": [45000, 60000, 55000, 70000, 48000, 52000],
    "Experience": [2, 5, 3, 7, 1, 4]
})
df

      Name Department  Salary  Experience
0    Alice         HR   45000           2
1      Bob         IT   60000           5
2  Charlie    Finance   55000           3
3    David         IT   70000           7
4      Eva         HR   48000           1
5    Frank      Sales   52000           4

In [26]:
print(df.head(3))
print(df.tail(2))
print(df.shape)
print(df.columns)
print(df.dtypes)
print(df.info())
print(df.describe())

      Name Department  Salary  Experience
0    Alice         HR   45000           2
1      Bob         IT   60000           5
2  Charlie    Finance   55000           3
    Name Department  Salary  Experience
4    Eva         HR   48000           1
5  Frank      Sales   52000           4
(6, 4)
Index(['Name', 'Department', 'Salary', 'Experience'], dtype='str')
Name            str
Department      str
Salary        int64
Experience    int64
dtype: object
<class 'pandas.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Name        6 non-null      str
 1   Department  6 non-null      str
 2   Salary      6 non-null      int64
 3   Experience  6 non-null      int64
dtypes: int64(2), str(2)
memory usage: 324.0 bytes
None
             Salary  Experience
count      6.000000    6.000000
mean   55000.000000    3.666667
std     9033.271833    2.160247
min    45000.000000    1.000000
25%    49000.000000    2.250000
50%    53500.000000    3.500000
75%    58750.000000    4.750000
max    70000.000000    7.000000


# Pandas Challenge 5/100

## Topic: Selecting Data (`[]`, `loc`, `iloc`)

**Difficulty:** Easy (Placement Foundation)

### Tasks

1. Select only the `Name` column.
2. Select the `Name` and `Salary` columns together.
3. Select rows **1 to 3** using `loc`.
4. Select rows **1 to 3** using `iloc`.
5. Select the employee in row index `4` and the `Department` column using `loc`.
6. Select the value at **row position `2`** and **column position `3`** using `iloc`.
7. Select the single `Salary` value of **David** using `loc`.

In [27]:
df = pd.DataFrame({
    "Name": ["Alice", "Bob", "Charlie", "David", "Eva", "Frank"],
    "Department": ["HR", "IT", "Finance", "IT", "HR", "Sales"],
    "Salary": [45000, 60000, 55000, 70000, 48000, 52000],
    "Experience": [2, 5, 3, 7, 1, 4]
})
df

      Name Department  Salary  Experience
0    Alice         HR   45000           2
1      Bob         IT   60000           5
2  Charlie    Finance   55000           3
3    David         IT   70000           7
4      Eva         HR   48000           1
5    Frank      Sales   52000           4

In [28]:
print(df[["Name"]])
print(df[["Name", "Salary"]])
print(df.loc[0:2])
print(df.iloc[0:3])
print(df.loc[[4],["Department"]])
print(df.iloc[[2],[3]])
print(df.loc[[3],["Salary"]])

      Name
0    Alice
1      Bob
2  Charlie
3    David
4      Eva
5    Frank
      Name  Salary
0    Alice   45000
1      Bob   60000
2  Charlie   55000
3    David   70000
4      Eva   48000
5    Frank   52000
      Name Department  Salary  Experience
0    Alice         HR   45000           2
1      Bob         IT   60000           5
2  Charlie    Finance   55000           3
      Name Department  Salary  Experience
0    Alice         HR   45000           2
1      Bob         IT   60000           5
2  Charlie    Finance   55000           3
  Department
4         HR
   Experience
2           3
   Salary
3   70000

# Pandas Challenge 6/100

## Topic: Scalar Access (`at` and `iat`)

**Difficulty:** Easy (Placement Foundation)

### Tasks

1. Get Alice's `Salary` using `at`.
2. Get Charlie's `Experience` using `at`.
3. Get Eva's `Department` using `at`.
4. Get the value at row position `1`, column position `2` using `iat`.
5. Get the value at row position `5`, column position `0` using `iat`.
6. Print all five outputs.

In [29]:
df = pd.DataFrame({
    "Name": ["Alice", "Bob", "Charlie", "David", "Eva", "Frank"],
    "Department": ["HR", "IT", "Finance", "IT", "HR", "Sales"],
    "Salary": [45000, 60000, 55000, 70000, 48000, 52000],
    "Experience": [2, 5, 3, 7, 1, 4]
})
df

      Name Department  Salary  Experience
0    Alice         HR   45000           2
1      Bob         IT   60000           5
2  Charlie    Finance   55000           3
3    David         IT   70000           7
4      Eva         HR   48000           1
5    Frank      Sales   52000           4

In [30]:
print(df.at[0,"Salary"])
print(df.at[2,"Experience"])
print(df.at[4,"Department"])
print(df.iat[1,2])
print(df.iat[5,0])

45000
3
HR
60000
Frank


# Pandas Challenge 7/100

## Topic: Column Operations

**Difficulty:** Easy (Placement Foundation)

### Tasks

1. Display only the `Department` column.
2. Create a new column named `Bonus` equal to **10% of Salary**.
3. Create another column named `Total_Salary` equal to `Salary + Bonus`.
4. Display all unique departments.
5. Print the number of unique departments.
6. Print how many employees belong to each department using `value_counts()`.
7. Display the updated DataFrame.

In [31]:
df = pd.DataFrame({
    "Name": ["Alice", "Bob", "Charlie", "David", "Eva", "Frank"],
    "Department": ["HR", "IT", "Finance", "IT", "HR", "Sales"],
    "Salary": [45000, 60000, 55000, 70000, 48000, 52000],
    "Experience": [2, 5, 3, 7, 1, 4]
})
df

      Name Department  Salary  Experience
0    Alice         HR   45000           2
1      Bob         IT   60000           5
2  Charlie    Finance   55000           3
3    David         IT   70000           7
4      Eva         HR   48000           1
5    Frank      Sales   52000           4

In [32]:
print(df["Department"])
bonus=df["Salary"]/10
print(bonus)
total_salary=df["Salary"]+bonus
print(total_salary)
unique_dep=pd.unique(df["Department"])
print(unique_dep)
print(len(unique_dep))
print(df.value_counts("Department"))

0         HR
1         IT
2    Finance
3         IT
4         HR
5      Sales
Name: Department, dtype: str
0    4500.0
1    6000.0
2    5500.0
3    7000.0
4    4800.0
5    5200.0
Name: Salary, dtype: float64
0    49500.0
1    66000.0
2    60500.0
3    77000.0
4    52800.0
5    57200.0
Name: Salary, dtype: float64
<StringArray>
['HR', 'IT', 'Finance', 'Sales']
Length: 4, dtype: str
4
Department
HR         2
IT         2
Finance    1
Sales      1
Name: count, dtype: int64


# Pandas Challenge 8/100

## Topic: Row and Column Slicing

**Difficulty:** Easy (Placement Foundation)

### Tasks

1. Display the first **4** rows.
2. Display the last **3** rows.
3. Display rows **1 to 4** using `iloc`.
4. Display only the first **2** columns.
5. Display only the last **2** columns.
6. Display rows **2 to 5** and columns **1 to 3** using `iloc`.
7. Display rows **0 to 2** and only the `Name` and `Salary` columns using `loc`.

In [33]:
df = pd.DataFrame({
    "Name": ["Alice", "Bob", "Charlie", "David", "Eva", "Frank"],
    "Department": ["HR", "IT", "Finance", "IT", "HR", "Sales"],
    "Salary": [45000, 60000, 55000, 70000, 48000, 52000],
    "Experience": [2, 5, 3, 7, 1, 4]
})
df

      Name Department  Salary  Experience
0    Alice         HR   45000           2
1      Bob         IT   60000           5
2  Charlie    Finance   55000           3
3    David         IT   70000           7
4      Eva         HR   48000           1
5    Frank      Sales   52000           4

In [34]:
print(df.iloc[:4])
print(df.iloc[-3:])
print(df.iloc[1:4])
print(df.iloc[:,0:2])
print(df.iloc[:,-2:])
print(df.iloc[2:6, 1:4])
print(df.loc[0:2, ["Name", "Salary"]])

      Name Department  Salary  Experience
0    Alice         HR   45000           2
1      Bob         IT   60000           5
2  Charlie    Finance   55000           3
3    David         IT   70000           7
    Name Department  Salary  Experience
3  David         IT   70000           7
4    Eva         HR   48000           1
5  Frank      Sales   52000           4
      Name Department  Salary  Experience
1      Bob         IT   60000           5
2  Charlie    Finance   55000           3
3    David         IT   70000           7
      Name Department
0    Alice         HR
1      Bob         IT
2  Charlie    Finance
3    David         IT
4      Eva         HR
5    Frank      Sales
   Salary  Experience
0   45000           2
1   60000           5
2   55000           3
3   70000           7
4   48000           1
5   52000           4
  Department  Salary  Experience
2    Finance   55000           3
3         IT   70000           7
4         HR   48000           1
5      Sales   52000           4
      Name  Salary
0    Alice   45000
1      Bob   60000
2  Charlie   55000


# Pandas Challenge 9/100

## Topic: Boolean Filtering

**Difficulty:** Medium (Placement Foundation)

### Tasks

1. Show employees whose **Salary is greater than 50,000**.
2. Show employees whose **Department is IT**.
3. Show employees whose **Experience is at least 3 years**.
4. Show employees whose **Salary is greater than 50,000 AND Experience is at least 3 years**.
5. Show employees whose **Department is HR OR Sales**.
6. Show employees whose **Department is NOT IT**.
7. Show only the `Name` and `Salary` columns for employees whose **Salary is at least 55,000**.

In [35]:
df = pd.DataFrame({
    "Name": ["Alice", "Bob", "Charlie", "David", "Eva", "Frank"],
    "Department": ["HR", "IT", "Finance", "IT", "HR", "Sales"],
    "Salary": [45000, 60000, 55000, 70000, 48000, 52000],
    "Experience": [2, 5, 3, 7, 1, 4]
})
df

      Name Department  Salary  Experience
0    Alice         HR   45000           2
1      Bob         IT   60000           5
2  Charlie    Finance   55000           3
3    David         IT   70000           7
4      Eva         HR   48000           1
5    Frank      Sales   52000           4

In [36]:
salary_mask=df.Salary>50000
IT_mask=df.Department=="IT"
exp_mask=df.Experience>=3
notIT_mask=df.Department!="IT"

print(df.iloc[:,:][salary_mask])
print(df.iloc[:,:][IT_mask])
print(df.iloc[:,:][exp_mask])
print(df[(df["Salary"] > 50000) & (df["Experience"] >= 3)])
print(df[(df["Department"] == "HR") | (df["Department"] == "Sales")])
print(df.iloc[:,:][notIT_mask])
print(df.loc[df["Salary"] >= 55000, ["Name", "Salary"]])

      Name Department  Salary  Experience
1      Bob         IT   60000           5
2  Charlie    Finance   55000           3
3    David         IT   70000           7
5    Frank      Sales   52000           4
    Name Department  Salary  Experience
1    Bob         IT   60000           5
3  David         IT   70000           7
      Name Department  Salary  Experience
1      Bob         IT   60000           5
2  Charlie    Finance   55000           3
3    David         IT   70000           7
5    Frank      Sales   52000           4
      Name Department  Salary  Experience
1      Bob         IT   60000           5
2  Charlie    Finance   55000           3
3    David         IT   70000           7
5    Frank      Sales   52000           4
    Name Department  Salary  Experience
0  Alice         HR   45000           2
4    Eva         HR   48000           1
5  Frank      Sales   52000           4
      Name Department  Salary  Experience
0    Alice         HR   45000           2
2  Charlie    Finance   55000           3
4      Eva         HR   48000           1
5    Frank      Sales   52000           4
      Name  Salary
1      Bob   60000
2  Charlie   55000
3    David   70000


# Pandas Challenge 10/100

## Topic: Advanced Filtering (`isin()`, `between()`, `query()`)

**Difficulty:** Medium (Placement Foundation)

### Tasks

1. Show employees whose **Department is either HR or Finance** using `isin()`.
2. Show employees whose **Salary is between 48,000 and 60,000** using `between()`.
3. Show employees whose **Experience is between 2 and 5 years** using `between()`.
4. Using `query()`, show employees whose **Salary is greater than 50,000 and Department is IT**.
5. Using `query()`, show employees whose **Experience is at least 3 years and Salary is less than 70,000**.
6. Show only the `Name`, `Department`, and `Salary` columns for employees whose **Department is HR, Finance, or Sales**.
7. Show employees who are **not** in the HR department using `query()`.

In [37]:
df = pd.DataFrame({
    "Name": ["Alice", "Bob", "Charlie", "David", "Eva", "Frank"],
    "Department": ["HR", "IT", "Finance", "IT", "HR", "Sales"],
    "Salary": [45000, 60000, 55000, 70000, 48000, 52000],
    "Experience": [2, 5, 3, 7, 1, 4]
})
df

      Name Department  Salary  Experience
0    Alice         HR   45000           2
1      Bob         IT   60000           5
2  Charlie    Finance   55000           3
3    David         IT   70000           7
4      Eva         HR   48000           1
5    Frank      Sales   52000           4

In [61]:
print(df[df["Department"].isin(["HR", "Finance"])])
print(df[df["Salary"].between(48000, 60000)])
print(df[df["Experience"].between(2, 5)])
print(df.query("Salary > 50000 and Department == 'IT'"))
print(df.query("Salary < 70000 and Experience >= 3"))
hfs=df[df["Department"].isin(["HR", "Finance", "Sales"])]
print(hfs[["Name", "Salary", "Department"]])
print(df.query("Department != 'HR'"))

      Name Department  Salary  Experience
0    Alice         HR   45000           2
2  Charlie    Finance   55000           3
4      Eva         HR   48000           1
      Name Department  Salary  Experience
1      Bob         IT   60000           5
2  Charlie    Finance   55000           3
4      Eva         HR   48000           1
5    Frank      Sales   52000           4
      Name Department  Salary  Experience
0    Alice         HR   45000           2
1      Bob         IT   60000           5
2  Charlie    Finance   55000           3
5    Frank      Sales   52000           4
    Name Department  Salary  Experience
1    Bob         IT   60000           5
3  David         IT   70000           7
      Name Department  Salary  Experience
1      Bob         IT   60000           5
2  Charlie    Finance   55000           3
5    Frank      Sales   52000           4
      Name  Salary Department
0    Alice   45000         HR
2  Charlie   55000    Finance
4      Eva   48000         HR
5    Frank   52000      Sales
      Name Department  Salary  Experience
1      Bob         IT   60000           5
2  Charlie    Finance   55000           3
3    David         IT   70000           7
5    Frank      Sales   52000           4


# Pandas Challenge 11/100

## Topic: String Filtering (`str.contains()`, `startswith()`, `endswith()`)

**Difficulty:** Medium (Placement Foundation)

### Tasks

1. Show employees whose **Name starts with "A"**.
2. Show employees whose **Name ends with "a"**.
3. Show employees whose **Department contains "IT"**.
4. Show employees whose **Name contains the letter "a"** (case-insensitive).
5. Show employees whose **Department does not contain "HR"**.
6. Display only the `Name` and `Department` columns for employees whose **Name starts with "D" or "E"**.
7. Print all employee names in **uppercase** without modifying the original DataFrame.

In [64]:
df = pd.DataFrame({
    "Name": ["Alice", "Bob", "Charlie", "David", "Eva", "Frank"],
    "Department": ["HR", "IT", "Finance", "IT", "HR", "Sales"],
    "Salary": [45000, 60000, 55000, 70000, 48000, 52000],
    "Experience": [2, 5, 3, 7, 1, 4]
})
df

      Name Department  Salary  Experience
0    Alice         HR   45000           2
1      Bob         IT   60000           5
2  Charlie    Finance   55000           3
3    David         IT   70000           7
4      Eva         HR   48000           1
5    Frank      Sales   52000           4

In [73]:
print(df[df["Name"].str.endswith("a")])
print(df[df["Department"].str.contains("IT")])
print(df[df["Name"].str.contains("a")])
print(df[df["Department"].str.contains("HR")])

  Name Department  Salary  Experience
4  Eva         HR   48000           1
    Name Department  Salary  Experience
1    Bob         IT   60000           5
3  David         IT   70000           7
      Name Department  Salary  Experience
2  Charlie    Finance   55000           3
3    David         IT   70000           7
4      Eva         HR   48000           1
5    Frank      Sales   52000           4
    Name Department  Salary  Experience
0  Alice         HR   45000           2
4    Eva         HR   48000           1


# Pandas Challenge 12/100

## Topic: Sorting Data

**Difficulty:** Medium (Placement Foundation)

### Tasks

1. Sort the DataFrame by `Salary` in ascending order.
2. Sort the DataFrame by `Salary` in descending order.
3. Sort the DataFrame by `Experience` in descending order.
4. Display the top 3 employees with the highest salaries.
5. Display the 2 employees with the lowest salaries.
6. Sort the DataFrame first by `Department` (ascending) and then by `Salary` (descending).
7. Display only the `Name` and `Salary` columns of the top 3 highest-paid employees.

In [74]:
df = pd.DataFrame({
    "Name": ["Alice", "Bob", "Charlie", "David", "Eva", "Frank"],
    "Department": ["HR", "IT", "Finance", "IT", "HR", "Sales"],
    "Salary": [45000, 60000, 55000, 70000, 48000, 52000],
    "Experience": [2, 5, 3, 7, 1, 4]
})
df

      Name Department  Salary  Experience
0    Alice         HR   45000           2
1      Bob         IT   60000           5
2  Charlie    Finance   55000           3
3    David         IT   70000           7
4      Eva         HR   48000           1
5    Frank      Sales   52000           4

In [ ]:
print(df.sort_values("Salary"))
print(df.sort_values("Salary", ascending=False))
print(df.sort_values("Experience", ascending=False))
largest_3=df.nlargest(3, "Salary")
print(largest_3)
print(df.nsmallest(2, "Experience"))
df.sort_values(
    by=["Department", "Salary"],
    ascending=[True, False]
)
print(largest_3[["Name", "Salary"]])

      Name Department  Salary  Experience
0    Alice         HR   45000           2
4      Eva         HR   48000           1
5    Frank      Sales   52000           4
2  Charlie    Finance   55000           3
1      Bob         IT   60000           5
3    David         IT   70000           7
      Name Department  Salary  Experience
3    David         IT   70000           7
1      Bob         IT   60000           5
2  Charlie    Finance   55000           3
5    Frank      Sales   52000           4
4      Eva         HR   48000           1
0    Alice         HR   45000           2
      Name Department  Salary  Experience
3    David         IT   70000           7
1      Bob         IT   60000           5
5    Frank      Sales   52000           4
2  Charlie    Finance   55000           3
0    Alice         HR   45000           2
4      Eva         HR   48000           1
      Name Department  Salary  Experience
3    David         IT   70000           7
1      Bob         IT   60000           5
2  Charlie    Finance   55000           3
    Name Department  Salary  Experience
4    Eva         HR   48000           1
0  Alice         HR   45000           2
      Name  Salary
3    David   70000
1      Bob   60000
2  Charlie   55000


# Pandas Challenge 13/100

## Topic: Missing Values (`NaN`)

**Difficulty:** Medium (Placement Foundation)

### Tasks

1. Count the missing values in each column.
2. Display only the rows where `Salary` is missing.
3. Fill missing `Salary` values with the **mean Salary** and store the result in `df_mean`.
4. Fill missing `Experience` values with the value **0** and store the result in `df_exp`.
5. Remove all rows containing any missing value and store the result in `df_clean`.
6. Print the shape of the original DataFrame and `df_clean`.
7. Verify that `df_mean` has no missing values in the `Salary` column.

In [83]:
import numpy as np

df = pd.DataFrame({
    "Name": ["Alice", "Bob", "Charlie", "David", "Eva", "Frank"],
    "Department": ["HR", "IT", "Finance", "IT", "HR", "Sales"],
    "Salary": [45000, np.nan, 55000, 70000, np.nan, 52000],
    "Experience": [2, 5, np.nan, 7, 1, np.nan]
})

df

      Name Department   Salary  Experience
0    Alice         HR  45000.0         2.0
1      Bob         IT      NaN         5.0
2  Charlie    Finance  55000.0         NaN
3    David         IT  70000.0         7.0
4      Eva         HR      NaN         1.0
5    Frank      Sales  52000.0         NaN

In [96]:
print(df.isnull().sum())
print(df[df["Salary"].isnull()])
df_mean = df.copy()
df_mean["Salary"] = df_mean["Salary"].fillna(df_mean["Salary"].mean())
print(df_mean)
df_exp = df.copy()
df_exp["Experience"] = df_exp["Experience"].fillna(0)
print(df_exp)
df_clean = df.dropna()
print(df_clean)
print("Original Shape:", df.shape)
print("Clean Shape:", df_clean.shape)
print(df_mean["Salary"].isnull().sum())

Name          0
Department    0
Salary        2
Experience    2
dtype: int64
  Name Department  Salary  Experience
1  Bob         IT     NaN         5.0
4  Eva         HR     NaN         1.0
      Name Department   Salary  Experience
0    Alice         HR  45000.0         2.0
1      Bob         IT  55500.0         5.0
2  Charlie    Finance  55000.0         NaN
3    David         IT  70000.0         7.0
4      Eva         HR  55500.0         1.0
5    Frank      Sales  52000.0         NaN
      Name Department   Salary  Experience
0    Alice         HR  45000.0         2.0
1      Bob         IT      NaN         5.0
2  Charlie    Finance  55000.0         0.0
3    David         IT  70000.0         7.0
4      Eva         HR      NaN         1.0
5    Frank      Sales  52000.0         0.0
    Name Department   Salary  Experience
0  Alice         HR  45000.0         2.0
3  David         IT  70000.0         7.0
Original Shape: (6, 4)
Clean Shape: (2, 4)
0


# Pandas Challenge 14/100

## Topic: Duplicate Data

**Difficulty:** Medium (Placement Foundation)

### Tasks

1. Display which rows are duplicates using `duplicated()`.
2. Print the total number of duplicate rows.
3. Remove duplicate rows and store the result in `df_unique`.
4. Remove duplicates based only on the `Name` column and keep the **first** occurrence.
5. Remove duplicates based only on the `Name` column and keep the **last** occurrence.
6. Remove **all** duplicate `Name` entries (keep none of the repeated names).
7. Print the shapes of the original DataFrame and `df_unique`.

In [4]:
df = pd.DataFrame({
    "Name": ["Alice", "Bob", "Charlie", "Bob", "Eva", "Alice", "Frank"],
    "Department": ["HR", "IT", "Finance", "IT", "HR", "HR", "Sales"],
    "Salary": [45000, 60000, 55000, 60000, 48000, 45000, 52000],
    "Experience": [2, 5, 3, 5, 1, 2, 4]
})
df

      Name Department  Salary  Experience
0    Alice         HR   45000           2
1      Bob         IT   60000           5
2  Charlie    Finance   55000           3
3      Bob         IT   60000           5
4      Eva         HR   48000           1
5    Alice         HR   45000           2
6    Frank      Sales   52000           4

In [18]:
print(df[df.duplicated()])
print(df.duplicated().sum())
df_unique=df.drop_duplicates()
print(df_unique)
unique_on_name_first=df.drop_duplicates(subset="Name", keep="first")
print(unique_on_name_first)
unique_on_name_last=df.drop_duplicates(subset="Name", keep="last")
print(unique_on_name_last)
unique_on_name=df.drop_duplicates(subset="Name")
# df.drop_duplicates(subset="Name", keep=False)
print(unique_on_name)
print(np.shape(df), np.shape(df_unique))

    Name Department  Salary  Experience
3    Bob         IT   60000           5
5  Alice         HR   45000           2
2
      Name Department  Salary  Experience
0    Alice         HR   45000           2
1      Bob         IT   60000           5
2  Charlie    Finance   55000           3
4      Eva         HR   48000           1
6    Frank      Sales   52000           4
      Name Department  Salary  Experience
0    Alice         HR   45000           2
1      Bob         IT   60000           5
2  Charlie    Finance   55000           3
4      Eva         HR   48000           1
6    Frank      Sales   52000           4
      Name Department  Salary  Experience
2  Charlie    Finance   55000           3
3      Bob         IT   60000           5
4      Eva         HR   48000           1
5    Alice         HR   45000           2
6    Frank      Sales   52000           4
      Name Department  Salary  Experience
0    Alice         HR   45000           2
1      Bob         IT   60000           5
2  Charlie    Finance   55000           3
4      Eva         HR   48000           1
6    Frank      Sales   52000           4
(7, 4) (5, 4)

# Pandas Challenge 15/100

## Topic: Renaming & Modifying Columns

**Difficulty:** Medium (Placement Foundation)

### Tasks

1. Rename `Salary` to `Monthly_Salary` and store the result in `df1`.
2. Rename `Department` to `Dept` using `inplace=True` on a copy named `df2`.
3. Convert the `Experience` column to `float` in `df1`.
4. Insert a new column `Bonus` immediately after `Monthly_Salary` containing **10%** of `Monthly_Salary`.
5. Remove the `Dept` column from `df2` using `drop()`.
6. Remove the `Experience` column from `df1` using `pop()` and store it in a variable named `exp_removed`.
7. Print `df1`, `df2`, and `exp_removed`.

In [34]:
df = pd.DataFrame({
    "Name": ["Alice", "Bob", "Charlie", "David", "Eva", "Frank"],
    "Department": ["HR", "IT", "Finance", "IT", "HR", "Sales"],
    "Salary": [45000, 60000, 55000, 70000, 48000, 52000],
    "Experience": [2, 5, 3, 5, 1, 4]
})
df

      Name Department  Salary  Experience
0    Alice         HR   45000           2
1      Bob         IT   60000           5
2  Charlie    Finance   55000           3
3    David         IT   70000           5
4      Eva         HR   48000           1
5    Frank      Sales   52000           4

In [63]:

df1 = df.rename(columns={"Salary": "Monthly_Salary"})
print(df1)
df2 = df.copy()
df2.rename(columns={"Department": "Dept"}, inplace=True)
print(df2)
df1["Experience"] = df1["Experience"].astype(float)
print(df1)
bonus_index = df1.columns.get_loc("Monthly_Salary") + 1
df1.insert(bonus_index, "Bonus", df1["Monthly_Salary"] /10)
print(df1)
df2 = df2.drop(columns=["Dept"])
print(df2)
exp_removed = df1.pop("Experience")
print(df1)


print(exp_removed)

      Name Department   Bonus  Monthly_Salary  Experience
0    Alice         HR  4500.0           45000           2
1      Bob         IT  6000.0           60000           5
2  Charlie    Finance  5500.0           55000           3
3    David         IT  7000.0           70000           5
4      Eva         HR  4800.0           48000           1
5    Frank      Sales  5200.0           52000           4
      Name     Dept   Bonus  Salary  Experience
0    Alice       HR  4500.0   45000           2
1      Bob       IT  6000.0   60000           5
2  Charlie  Finance  5500.0   55000           3
3    David       IT  7000.0   70000           5
4      Eva       HR  4800.0   48000           1
5    Frank    Sales  5200.0   52000           4
      Name Department   Bonus  Monthly_Salary  Experience
0    Alice         HR  4500.0           45000         2.0
1      Bob         IT  6000.0           60000         5.0
2  Charlie    Finance  5500.0           55000         3.0
3    David         IT  7000.0           70000         5.0
4      Eva         HR  4800.0           48000         1.0
5    Frank      Sales  5200.0           52000         4.0

ValueError: cannot insert Bonus, already exists

# Pandas Challenge 16/100

## Topic: String Operations (Data Cleaning)

**Difficulty:** Medium (Placement Foundation)

### Tasks

1. Remove leading and trailing spaces from the `Name` column.
2. Convert all names to **Title Case**.
3. Convert the `Department` column to **uppercase**.
4. Replace `"Finance"` with `"FIN"` in the `Department` column.
5. Split the `Email` column into two new columns: `Username` and `Domain`.
6. Create a new column `Name_Length` containing the length of each employee's name (after cleaning).
7. Display the cleaned DataFrame.

In [4]:
df = pd.DataFrame({
    "Name": [" alice ", "BOB", " Charlie", "DAVID ", " eva ", "Frank"],
    "Department": ["hr", "IT", "Finance", "it", "HR", "sales"],
    "Email": [
        "alice@gmail.com",
        "bob@yahoo.com",
        "charlie@company.com",
        "david@gmail.com",
        "eva@outlook.com",
        "frank@company.com"
    ]
})
df

       Name Department                Email
0    alice          hr      alice@gmail.com
1       BOB         IT        bob@yahoo.com
2   Charlie    Finance  charlie@company.com
3    DAVID          it      david@gmail.com
4      eva          HR      eva@outlook.com
5     Frank      sales    frank@company.com

In [6]:
df["Name"] = df["Name"].str.strip().str.title()
df["Department"] = df["Department"].str.upper()
df["Department"] = df["Department"].str.replace("FINANCE", "FIN")
df[["Username", "Domain"]] = df["Email"].str.split("@", expand=True)
df["Name_Length"] = df["Name"].str.len()
print(df)

      Name Department                Email Username       Domain  Name_Length
0    Alice         HR      alice@gmail.com    alice    gmail.com            5
1      Bob         IT        bob@yahoo.com      bob    yahoo.com            3
2  Charlie        FIN  charlie@company.com  charlie  company.com            7
3    David         IT      david@gmail.com    david    gmail.com            5
4      Eva         HR      eva@outlook.com      eva  outlook.com            3
5    Frank      SALES    frank@company.com    frank  company.com            5


# Pandas Challenge 17/100

## Topic: `apply()`, `map()`, and `lambda`

**Difficulty:** Medium (Placement Level)

### Tasks

1. Create a new column `Bonus` that is **10%** of `Salary` using `apply()` with `lambda`.
2. Create a new column `Total_Salary` equal to `Salary + Bonus`.
3. Use `map()` to convert the `Department` values as follows:
   - `HR` → `Human Resources`
   - `IT` → `Information Technology`
   - `Finance` → `Finance Department`
   - `Sales` → `Sales Department`
4. Create a new column `Grade` based on `Salary`:
   - `Salary >= 65000` → `"A"`
   - `Salary >= 55000` → `"B"`
   - Otherwise → `"C"`
5. Use `apply()` to create a new column `Experience_Level`:
   - `Experience >= 5` → `"Senior"`
   - Otherwise → `"Junior"`
6. Display the final DataFrame.

In [10]:
df = pd.DataFrame({
    "Name": ["Alice", "Bob", "Charlie", "David", "Eva", "Frank"],
    "Department": ["HR", "IT", "Finance", "IT", "HR", "Sales"],
    "Salary": [45000, 60000, 55000, 70000, 48000, 52000],
    "Experience": [2, 5, 3, 7, 1, 4]
})
df

      Name Department  Salary  Experience
0    Alice         HR   45000           2
1      Bob         IT   60000           5
2  Charlie    Finance   55000           3
3    David         IT   70000           7
4      Eva         HR   48000           1
5    Frank      Sales   52000           4

In [13]:
df['Bonus'] = df['Salary'].apply(lambda x: x * 0.10)
df['Total_Salary'] = df['Salary'] + df['Bonus']
dept_mapping = {
"HR":"Human Resources",
"IT":"Information Technology",
"Finance": "Finance Department",
"Sales": "Sales Department"
}
df['Department'] = df['Department'].map(dept_mapping)
df['Grade'] = df['Salary'].apply(lambda x: "A" if x >= 65000 else ("B" if x >= 55000 else "C"))
df['Experience_Level'] = df['Experience'].apply(lambda x: "Senior" if x >= 5 else "Junior")
print(df)

      Name              Department  Salary  Experience   Bonus  Total_Salary  \
0    Alice         Human Resources   45000           2  4500.0       49500.0
1      Bob  Information Technology   60000           5  6000.0       66000.0
2  Charlie      Finance Department   55000           3  5500.0       60500.0
3    David  Information Technology   70000           7  7000.0       77000.0
4      Eva         Human Resources   48000           1  4800.0       52800.0
5    Frank        Sales Department   52000           4  5200.0       57200.0

  Grade Experience_Level
0     C           Junior
1     B           Senior
2     B           Junior
3     A           Senior
4     C           Junior
5     C           Junior

# Pandas Challenge 18/100

## Topic: GroupBy (Part 1)

**Difficulty:** Medium (Placement Level)

### Tasks

1. Find the **average Salary** for each Department.
2. Find the **maximum Salary** for each Department.
3. Find the **minimum Experience** for each Department.
4. Count how many employees are in each Department.
5. Find the **total Salary** paid by each Department.
6. Using `agg()`, display for each Department:
   - Mean Salary
   - Maximum Salary
   - Minimum Salary
   - Average Experience
7. Find which Department has the **highest total Salary**.

In [14]:
df = pd.DataFrame({
    "Name": ["Alice", "Bob", "Charlie", "David", "Eva", "Frank", "Grace", "Henry"],
    "Department": ["HR", "IT", "Finance", "IT", "HR", "Sales", "Finance", "IT"],
    "Salary": [45000, 60000, 55000, 70000, 48000, 52000, 65000, 75000],
    "Experience": [2, 5, 3, 7, 1, 4, 6, 8]
})
df

      Name Department  Salary  Experience
0    Alice         HR   45000           2
1      Bob         IT   60000           5
2  Charlie    Finance   55000           3
3    David         IT   70000           7
4      Eva         HR   48000           1
5    Frank      Sales   52000           4
6    Grace    Finance   65000           6
7    Henry         IT   75000           8

In [18]:
avg_salary = df.groupby('Department')['Salary'].mean()
print(avg_salary)
max_salary = df.groupby('Department')['Salary'].max()
print(max_salary)
min_exp = df.groupby('Department')['Experience'].min()
print(min_exp)
emp_count = df.groupby('Department')['Salary'].count()
print(emp_count)
total_salary = df.groupby('Department')['Salary'].sum()
print(total_salary)
dept_summary = df.groupby('Department').agg(
Mean_Salary=('Salary', 'mean'),
Max_Salary=('Salary', 'max'),
Min_Salary=('Salary', 'min'),
Avg_Experience=('Experience', 'mean')
)
print(dept_summary)

Department
Finance    60000.000000
HR         46500.000000
IT         68333.333333
Sales      52000.000000
Name: Salary, dtype: float64
Department
Finance    65000
HR         48000
IT         75000
Sales      52000
Name: Salary, dtype: int64
Department
Finance    3
HR         1
IT         5
Sales      4
Name: Experience, dtype: int64
Department
Finance    2
HR         2
IT         3
Sales      1
Name: Salary, dtype: int64
Department
Finance    120000
HR          93000
IT         205000
Sales       52000
Name: Salary, dtype: int64
             Mean_Salary  Max_Salary  Min_Salary  Avg_Experience
Department
Finance     60000.000000       65000       55000        4.500000
HR          46500.000000       48000       45000        1.500000
IT          68333.333333       75000       60000        6.666667
Sales       52000.000000       52000       52000        4.000000

# Pandas Challenge 20/100

## Topic: Pivot Tables

**Difficulty:** Medium (Placement Level)

### Tasks

1. Create a pivot table showing the **average Salary** for each `Department`.
2. Create a pivot table showing the **average Salary** for each `Department` and `Gender`.
3. Create a pivot table showing the **total Salary** for each `Department` and `Gender`.
4. Create a pivot table showing the **maximum Experience** for each `Department`.
5. Replace any missing values in the pivot table from Task 3 with `0`.
6. Create a pivot table showing the **employee count** for each `Department` and `Gender`.
7. Which department has the highest average salary according to your pivot table?

In [20]:
df = pd.DataFrame({
    "Name": ["Alice", "Bob", "Charlie", "David", "Eva", "Frank", "Grace", "Henry", "Ivy", "Jack"],
    "Department": ["HR", "IT", "Finance", "IT", "HR", "Sales", "Finance", "IT", "Sales", "HR"],
    "Gender": ["F", "M", "M", "M", "F", "M", "F", "M", "F", "M"],
    "Salary": [45000, 60000, 55000, 70000, 48000, 52000, 65000, 75000, 58000, 50000],
    "Experience": [2, 5, 3, 7, 1, 4, 6, 8, 5, 3]
})
df

      Name Department Gender  Salary  Experience
0    Alice         HR      F   45000           2
1      Bob         IT      M   60000           5
2  Charlie    Finance      M   55000           3
3    David         IT      M   70000           7
4      Eva         HR      F   48000           1
5    Frank      Sales      M   52000           4
6    Grace    Finance      F   65000           6
7    Henry         IT      M   75000           8
8      Ivy      Sales      F   58000           5
9     Jack         HR      M   50000           3

In [22]:
task_1 = df.pivot_table(values='Salary', index='Department', aggfunc='mean')
print(task_1)
task_2 = df.pivot_table(values='Salary', index='Department', columns='Gender', aggfunc='mean')
print(task_2)
task_3 = df.pivot_table(values='Salary', index='Department', columns='Gender', aggfunc='sum')
print(task_3)
task_4 = df.pivot_table(values='Experience', index='Department', aggfunc='max')
print(task_4)
task_5 = df.pivot_table(values='Salary', index='Department', columns='Gender', aggfunc='sum', fill_value=0)
print(task_5)
task_6 = df.pivot_table(values='Salary', index='Department', columns='Gender', aggfunc='count')
print(task_6)
highest_avg_salary_dept = task_1['Salary'].idxmax()
print(highest_avg_salary_dept)

                  Salary
Department
Finance     60000.000000
HR          47666.666667
IT          68333.333333
Sales       55000.000000
Gender            F             M
Department
Finance     65000.0  55000.000000
HR          46500.0  50000.000000
IT              NaN  68333.333333
Sales       58000.0  52000.000000
Gender            F         M
Department
Finance     65000.0   55000.0
HR          93000.0   50000.0
IT              NaN  205000.0
Sales       58000.0   52000.0
            Experience
Department
Finance              6
HR                   3
IT                   8
Sales                5
Gender          F       M
Department
Finance     65000   55000
HR          93000   50000
IT              0  205000
Sales       58000   52000
Gender        F    M
Department
Finance     1.0  1.0
HR          2.0  1.0
IT          NaN  3.0
Sales       1.0  1.0
IT

# Pandas Challenge 21/100

## Topic: Merge, Join & Concat

**Difficulty:** Medium-Hard (Placement Level)

### Tasks

1. Perform an **inner merge** of `employees` and `departments` using `Department_ID`.
2. Perform a **left merge** of `employees` and `departments`.
3. Perform a **right merge** of `employees` and `departments`.
4. Perform an **outer merge** of `employees` and `departments`.
5. Merge `employees` with `bonus` using `Employee_ID`.
6. Concatenate `sales_q1` and `sales_q2` vertically.
7. Concatenate `sales_q1` and `sales_q2` horizontally.

In [30]:
employees = pd.DataFrame({
    "Employee_ID": [101, 102, 103, 104, 105],
    "Name": ["Alice", "Bob", "Charlie", "David", "Eva"],
    "Department_ID": [1, 2, 2, 3, 4]
})
departments = pd.DataFrame({
    "Department_ID": [1, 2, 3, 5],
    "Department": ["HR", "IT", "Finance", "Marketing"]
})
bonus = pd.DataFrame({
    "Employee_ID": [101, 103, 105],
    "Bonus": [5000, 7000, 4000]
})
sales_q1 = pd.DataFrame({
    "Sales": [120, 150, 180]
})
sales_q2 = pd.DataFrame({
    "Sales": [200, 170, 160]
})
df1=employees.merge(departments, on="Department_ID", how="inner")
print(df1)
df2=employees.merge(departments, on="Department_ID", how="left")
print(df2)
df3=employees.merge(departments, on="Department_ID", how="right")
print(df3)
df4=employees.merge(departments, on="Department_ID", how="outer")
print(df4)
df5=employees.merge(bonus, on="Employee_ID", how="left")
print(df5)
print(pd.concat([df1, df2]))
print(pd.concat([df1, df2], axis=1))

   Employee_ID     Name  Department_ID Department
0          101    Alice              1         HR
1          102      Bob              2         IT
2          103  Charlie              2         IT
3          104    David              3    Finance
   Employee_ID     Name  Department_ID Department
0          101    Alice              1         HR
1          102      Bob              2         IT
2          103  Charlie              2         IT
3          104    David              3    Finance
4          105      Eva              4        NaN
   Employee_ID     Name  Department_ID Department
0        101.0    Alice              1         HR
1        102.0      Bob              2         IT
2        103.0  Charlie              2         IT
3        104.0    David              3    Finance
4          NaN      NaN              5  Marketing
   Employee_ID     Name  Department_ID Department
0        101.0    Alice              1         HR
1        102.0      Bob              2         IT
2        103.0  Charlie              2         IT
3        104.0    David              3    Finance
4        105.0      Eva              4        NaN
5          NaN      NaN              5  Marketing
   Employee_ID     Name  Department_ID   Bonus
0          101    Alice              1  5000.0
1          102      Bob              2     NaN
2          103  Charlie              2  7000.0
3          104    David              3     NaN
4          105      Eva              4  4000.0
   Employee_ID     Name  Department_ID Department
0          101    Alice              1         HR
1          102      Bob              2         IT
2          103  Charlie              2         IT
3          104    David              3    Finance
0          101    Alice              1         HR
1          102      Bob              2         IT
2          103  Charlie              2         IT
3          104    David              3    Finance
4          105      Eva              4        NaN
   Employee_ID     Name  Department_ID Department  Employee_ID     Name  \
0        101.0    Alice            1.0         HR          101    Alice
1        102.0      Bob            2.0         IT          102      Bob
2        103.0  Charlie            2.0         IT          103  Charlie
3        104.0    David            3.0    Finance          104    David
4          NaN      NaN            NaN        NaN          105      Eva

   Department_ID Department
0              1         HR
1              2         IT
2              2         IT
3              3    Finance
4              4        NaN

# Pandas Challenge 22/100

## Topic: Reshaping Data

**Difficulty:** Medium-Hard (Placement Level)

### Tasks

1. Convert the DataFrame from **wide** format to **long** format using `melt()`.
2. Name the new columns `Subject` and `Marks`.
3. Melt only the subject columns while keeping `Name` unchanged.
4. Set `Name` as the index and use `stack()`.
5. Convert the stacked result back using `unstack()`.
6. Use `explode()` on the `Skills` column.
7. Display all intermediate results.

In [31]:
marks_df = pd.DataFrame({
    "Name": ["Alice", "Bob", "Charlie"],
    "Math": [90, 80, 85],
    "Science": [85, 88, 92],
    "English": [78, 91, 87]
})

skills_df = pd.DataFrame({
    "Name": ["Alice", "Bob", "Charlie"],
    "Skills": [
        ["Python", "SQL"],
        ["Excel", "Power BI"],
        ["Python", "Pandas", "NumPy"]
    ]
})

melted_df = pd.melt(
    marks_df, 
    id_vars=['Name'], 
    value_vars=['Math', 'Science', 'English'], 
    var_name='Subject', 
    value_name='Marks'
)
print(melted_df)

stacked_series = marks_df.set_index('Name').stack()
print(stacked_series)

unstacked_df = stacked_series.unstack()
print(unstacked_df)

exploded_df = skills_df.explode('Skills')
print(exploded_df.reset_index(drop=True))

      Name  Subject  Marks
0    Alice     Math     90
1      Bob     Math     80
2  Charlie     Math     85
3    Alice  Science     85
4      Bob  Science     88
5  Charlie  Science     92
6    Alice  English     78
7      Bob  English     91
8  Charlie  English     87
Name
Alice    Math       90
         Science    85
         English    78
Bob      Math       80
         Science    88
         English    91
Charlie  Math       85
         Science    92
         English    87
dtype: int64
         Math  Science  English
Name
Alice      90       85       78
Bob        80       88       91
Charlie    85       92       87
      Name    Skills
0    Alice    Python
1    Alice       SQL
2      Bob     Excel
3      Bob  Power BI
4  Charlie    Python
5  Charlie    Pandas
6  Charlie     NumPy

# Pandas Challenge 23/100

## Topic: MultiIndex

**Difficulty:** Hard (Placement Level)

### Tasks

1. Create a MultiIndex using `Department` and `Gender`.
2. Display only the `IT` department using `loc`.
3. Display only the `Finance` department with `Gender = F`.
4. Swap the two index levels using `swaplevel()`.
5. Sort the swapped index using `sort_index()`.
6. Reset the MultiIndex back into normal columns.
7. Verify that `Department` and `Gender` are regular columns again.

In [36]:
import pandas as pd

df = pd.DataFrame({
    "Name": ["Alice", "Bob", "Charlie", "David", "Eva", "Frank", "Grace", "Henry"],
    "Department": ["HR", "IT", "Finance", "IT", "HR", "Sales", "Finance", "IT"],
    "Gender": ["F", "M", "F", "M", "F", "M", "F", "M"],
    "Salary": [45000, 60000, 65000, 70000, 48000, 52000, 68000, 75000],
    "Experience": [2, 5, 6, 7, 1, 4, 8, 9]
})
df_mi = df.set_index(['Department', 'Gender'])
it_dept = df_mi.loc['IT']
finance_f = df_mi.loc[('Finance', 'F')]
df_swapped = df_mi.swaplevel()
df_sorted = df_swapped.sort_index()
df_reset = df_sorted.reset_index()
columns_restored = 'Department' in df_reset.columns and 'Gender' in df_reset.columns
is_standard_index = isinstance(df_reset.index, pd.RangeIndex)
print(df_mi)
print(it_dept)
print(finance_f)
print(df_swapped)
print(df_sorted)
print(df_reset)
print(columns_restored)
print(is_standard_index)

                      Name  Salary  Experience
Department Gender
HR         F         Alice   45000           2
IT         M           Bob   60000           5
Finance    F       Charlie   65000           6
IT         M         David   70000           7
HR         F           Eva   48000           1
Sales      M         Frank   52000           4
Finance    F         Grace   68000           8
IT         M         Henry   75000           9
         Name  Salary  Experience
Gender
M         Bob   60000           5
M       David   70000           7
M       Henry   75000           9
                      Name  Salary  Experience
Department Gender
Finance    F       Charlie   65000           6
           F         Grace   68000           8
                      Name  Salary  Experience
Gender Department
F      HR            Alice   45000           2
M      IT              Bob   60000           5
F      Finance     Charlie   65000           6
M      IT            David   70000           7
F      HR              Eva   48000           1
M      Sales         Frank   52000           4
F      Finance       Grace   68000           8
M      IT            Henry   75000           9
                      Name  Salary  Experience
Gender Department
F      Finance     Charlie   65000           6
       Finance       Grace   68000           8
       HR            Alice   45000           2
       HR              Eva   48000           1
M      IT              Bob   60000           5
       IT            David   70000           7
       IT            Henry   75000           9
       Sales         Frank   52000           4
  Gender Department     Name  Salary  Experience
0      F    Finance  Charlie   65000           6
1      F    Finance    Grace   68000           8
2      F         HR    Alice   45000           2
3      F         HR      Eva   48000           1
4      M         IT      Bob   60000           5
5      M         IT    David   70000           7
6      M         IT    Henry   75000           9
7      M      Sales    Frank   52000           4
True
True

C:\Users\Prithwi's Aura\AppData\Local\Temp\ipykernel_25672\2349395690.py:12: PerformanceWarning: indexing past lexsort depth may impact performance.
  finance_f = df_mi.loc[('Finance', 'F')]

# Pandas Challenge 24/100

## Topic: Window Functions

**Difficulty:** Hard (Placement Level)

### Tasks

1. Calculate the running total of `Sales` using `cumsum()`.
2. Calculate the running maximum of `Sales`.
3. Calculate the running minimum of `Sales`.
4. Calculate a **3-day moving average** of `Sales`.
5. Calculate a **3-day moving sum** of `Sales`.
6. Calculate the expanding average of `Sales`.
7. Display the final DataFrame with all new columns.

In [38]:
df = pd.DataFrame({
    "Day": ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"],
    "Sales": [100, 120, 90, 150, 130, 170, 160]
})
# Task 1: Running total
df["Running_Total"] = df["Sales"].cumsum()

# Task 2: Running maximum
df["Running_Max"] = df["Sales"].cummax()

# Task 3: Running minimum
df["Running_Min"] = df["Sales"].cummin()

# Task 4: 3-day moving average
df["Moving_Avg_3"] = df["Sales"].rolling(window=3).mean()

# Task 5: 3-day moving sum
df["Moving_Sum_3"] = df["Sales"].rolling(window=3).sum()

# Task 6: Expanding average
df["Expanding_Avg"] = df["Sales"].expanding().mean()

# Task 7: Display final DataFrame
print(df)

   Day  Sales  Running_Total  Running_Max  Running_Min  Moving_Avg_3  \
0  Mon    100            100          100          100           NaN
1  Tue    120            220          120          100           NaN
2  Wed     90            310          120           90    103.333333
3  Thu    150            460          150           90    120.000000
4  Fri    130            590          150           90    123.333333
5  Sat    170            760          170           90    150.000000
6  Sun    160            920          170           90    153.333333

   Moving_Sum_3  Expanding_Avg
0           NaN     100.000000
1           NaN     110.000000
2         310.0     103.333333
3         360.0     115.000000
4         370.0     118.000000
5         450.0     126.666667
6         460.0     131.428571


# Pandas Challenge 25/100

## Topic: Feature Engineering (Final Challenge)

**Difficulty:** Hard (Placement Level)

### Tasks

1. Create an `Age_Group` column using `cut()` with these bins:
   - 20–30 → `"Young"`
   - 30–40 → `"Mid"`
   - 40–50 → `"Senior"`
2. Create a `Salary_Level` column using `qcut()` with **3 equal-frequency groups** labeled `"Low"`, `"Medium"`, and `"High"`.
3. Create a `Performance_Bonus` column:
   - If `Salary >= 60000`, bonus is **15%** of Salary.
   - Otherwise, bonus is **5%** of Salary.
4. Create a `Salary_per_Experience` column equal to `Salary / Experience`.
5. Create a `High_Performer` column:
   - `"Yes"` if `Salary >= 60000` **and** `Experience >= 5`.
   - Otherwise `"No"`.
6. Create a `Capped_Salary` column by limiting Salary to the range **45000–65000** using `clip()`.
7. Display the final DataFrame.

In [39]:
df = pd.DataFrame({
    "Name": ["Alice","Bob","Charlie","David","Eva","Frank","Grace","Henry"],
    "Age": [22,35,28,45,24,38,42,30],
    "Salary": [45000,60000,55000,70000,48000,52000,65000,75000],
    "Experience": [2,5,3,7,1,4,8,6]
})
# Task 1: Age_Group using cut()
df["Age_Group"] = pd.cut(
    df["Age"],
    bins=[20, 30, 40, 50],
    labels=["Young", "Mid", "Senior"],
    include_lowest=True
)

# Task 2: Salary_Level using qcut()
df["Salary_Level"] = pd.qcut(
    df["Salary"],
    q=3,
    labels=["Low", "Medium", "High"]
)

# Task 3: Performance_Bonus
df["Performance_Bonus"] = df["Salary"].apply(
    lambda x: x * 0.15 if x >= 60000 else x * 0.05
)

# Task 4: Salary_per_Experience
df["Salary_per_Experience"] = df["Salary"] / df["Experience"]

# Task 5: High_Performer
df["High_Performer"] = df.apply(
    lambda row: "Yes"
    if row["Salary"] >= 60000 and row["Experience"] >= 5
    else "No",
    axis=1
)

# Task 6: Capped_Salary
df["Capped_Salary"] = df["Salary"].clip(45000, 65000)

# Task 7: Display final DataFrame
print(df)

      Name  Age  Salary  Experience Age_Group Salary_Level  Performance_Bonus  \
0    Alice   22   45000           2     Young          Low             2250.0
1      Bob   35   60000           5       Mid       Medium             9000.0
2  Charlie   28   55000           3     Young       Medium             2750.0
3    David   45   70000           7    Senior         High            10500.0
4      Eva   24   48000           1     Young          Low             2400.0
5    Frank   38   52000           4       Mid          Low             2600.0
6    Grace   42   65000           8    Senior         High             9750.0
7    Henry   30   75000           6     Young         High            11250.0

   Salary_per_Experience High_Performer  Capped_Salary
0           22500.000000             No          45000
1           12000.000000            Yes          60000
2           18333.333333             No          55000
3           10000.000000            Yes          65000
4           48000.000000             No          48000
5           13000.000000             No          52000
6            8125.000000            Yes          65000
7           12500.000000            Yes          65000